<?php

class LoginTest extends \PHPUnit\Framework\TestCase
{
    public function setUp(): void
    {
        global $CONF;

        $this->cleanUp();

        $CONF['pacrypt'] = 'md5'; // crap

        db_execute("INSERT INTO domain(domain, description, transport) values ('example.com', 'test', 'foo')", [], true);

        db_execute(
            "INSERT INTO mailbox(username, password, name, maildir, local_part, domain) VALUES(:username, :password, :name, :maildir, :local_part, :domain)",
            [
                'username' => 'test@example.com',
                'password' => pacrypt('foobar'),
                'name' => 'test user',
                'maildir' => '/foo/bar',
                'local_part' => 'test',
                'domain' => 'example.com',
            ]);


        parent::setUp();
    }


    public function tearDown(): void
    {
        $this->cleanUp();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    private function cleanUp()
    {
        db_query('DELETE FROM alias');
        db_query('DELETE FROM alias_domain');
        db_query('DELETE FROM mailbox');
        db_query('DELETE FROM domain_admins');
        db_query('DELETE FROM domain');
    }

    public function testChangePassword()
    {
        $login = new Login('mailbox');

        $this->assertTrue($login->login('test@example.com', 'foobar'));

        // Can't change - current password wrong.
        try {
            $login->changePassword('test@example.com', 'foobar2', 'foobar2');
            $this->fail("Exception should have been thrown");
        } catch (\Exception $e) {
            $this->assertEquals("You didn't supply your current password!", $e->getMessage());
        }


        // Should change, current password correct.
        $this->assertTrue($login->changePassword('test@example.com', 'foobar2', 'foobar'));

        // Can't now login with the old password
        $this->assertFalse($login->login('test@example.com', 'foobar'));

        // Can login with the new one...
        $this->assertTrue($login->login('test@example.com', 'foobar2'));
    }


    public function testInvalidUsers()
    {
        $login = new Login('mailbox');

        $this->assertFalse($login->login('test', 'password'));
        $this->assertFalse($login->login('test', ''));
        $this->assertFalse($login->login('', ''));
    }


    public function testEmptyStringWithDovecot()
    {
        global $CONF;

        if (!file_exists('/usr/bin/doveadm')) {
            $this->markTestSkipped("/usr/bin/doveadm doesn't exist.");
        }

        $CONF['encrypt'] = 'dovecot:sha512';


        db_execute(
            "UPDATE mailbox SET password = :password WHERE username = :username",
            [
                'username' => 'test@example.com',
                'password' => '{SHA512}ClAmHr0aOQ/tK/Mm8mc8FFWCpjQtUjIElz0CGTN/gWFqgGmwElh89WNfaSXxtWw2AjDBmyc1AO4BPgMGAb8kJQ==', // pacrypt('foobar'),
            ]
        );

        $l = new Login('mailbox');
        $this->assertFalse($l->login('test@example.com', ''));

        $this->assertTrue($l->login('test@example.com', 'foobar'));

        $this->assertFalse($l->login('test@fails.com', 'foobar'));
    }

    public function testInvalidLogin()
    {
        $login = new Login('mailbox');

        $this->assertFalse($login->login('test', 'password'));
        $this->assertFalse($login->login('test', 'foobar'));
        $this->assertFalse($login->login('', ''));
    }

    public function testPasswordRecovery()
    {
        $login = new Login('mailbox');
        $this->assertFalse($login->generatePasswordRecoveryCode(''));
        $this->assertFalse($login->generatePasswordRecoveryCode('doesnotexist'));
        $this->assertNotEmpty($login->generatePasswordRecoveryCode('test@example.com'));
    }

    public function testAddAppPasswordIncorrectPassword()
    {
        $login = new Login('mailbox');
        $this->assertTrue($login->login('test@example.com', 'foobar'));

        $this->expectExceptionMessage("You didn't supply your current password!");
        $this->assertTrue($login->addAppPassword('test@example.com', 'fish', '1st-app-password', 'something'));
    }
    public function testAddAppPassword()
    {
        $login = new Login('mailbox');
        $this->assertTrue($login->login('test@example.com', 'foobar'));

        $this->assertTrue($login->addAppPassword('test@example.com', 'foobar', '1st-app-password', 'something'));
        $this->assertTrue($login->addAppPassword('test@example.com', 'foobar', '1st-app-password', 'something'));

        $rows = db_query_all('SELECT * FROM mailbox_app_password');

        $this->assertEquals(2, count($rows));

        foreach ($rows as $r) {
            $this->assertEquals('1st-app-password', $r['description']);
            $this->assertNotEmpty($r['password_hash']);
            $this->assertEquals('test@example.com', $r['username']);
        }
    }

    /**
     * Test admin login works via the admin table.
     */
    public function testAdminLogin()
    {
        db_execute(
            "INSERT INTO admin(username, password, superadmin, active) VALUES(:username, :password, :superadmin, :active)",
            [
                'username' => 'admin@example.com',
                'password' => pacrypt('adminpass'),
                'superadmin' => db_get_boolean(true),
                'active' => db_get_boolean(true),
            ]
        );

        $login = new Login('admin');
        $this->assertTrue($login->login('admin@example.com', 'adminpass'));
        $this->assertFalse($login->login('admin@example.com', 'wrongpass'));
        $this->assertFalse($login->login('nonexistent@example.com', 'adminpass'));

        db_query("DELETE FROM admin WHERE username = 'admin@example.com'");
    }

    /**
     * Test inactive mailbox cannot login.
     */
    public function testInactiveMailboxCannotLogin()
    {
        db_execute(
            "UPDATE mailbox SET active = :active WHERE username = :username",
            ['active' => db_get_boolean(false), 'username' => 'test@example.com']
        );

        $login = new Login('mailbox');
        $this->assertFalse($login->login('test@example.com', 'foobar'));

        // Reactivate
        db_execute(
            "UPDATE mailbox SET active = :active WHERE username = :username",
            ['active' => db_get_boolean(true), 'username' => 'test@example.com']
        );
    }

    /**
     * Test inactive admin cannot login.
     */
    public function testInactiveAdminCannotLogin()
    {
        db_execute(
            "INSERT INTO admin(username, password, superadmin, active) VALUES(:username, :password, :superadmin, :active)",
            [
                'username' => 'inactive@example.com',
                'password' => pacrypt('adminpass'),
                'superadmin' => db_get_boolean(false),
                'active' => db_get_boolean(false),
            ]
        );

        $login = new Login('admin');
        $this->assertFalse($login->login('inactive@example.com', 'adminpass'));

        db_query("DELETE FROM admin WHERE username = 'inactive@example.com'");
    }

    /**
     * Test Login constructor rejects invalid table names.
     */
    public function testInvalidTableThrows()
    {
        $this->expectException(\InvalidArgumentException::class);
        new Login('invalid_table');
    }

    /**
     * Test password recovery code can be verified.
     */
    public function testPasswordRecoveryCodeVerification()
    {
        $login = new Login('mailbox');
        $token = $login->generatePasswordRecoveryCode('test@example.com');

        $this->assertNotEmpty($token);
        $this->assertIsString($token);

        // Verify token is stored (hashed) in the database
        $row = db_query_one(
            "SELECT token, token_validity FROM " . table_by_key('mailbox') . " WHERE username = :username",
            ['username' => 'test@example.com']
        );
        $this->assertNotNull($row);
        $this->assertNotEmpty($row['token']);
        $this->assertNotEmpty($row['token_validity']);
    }
}
