#!/bin/bash

# This is a quick&dirty script to remove HTML from the language files.
# It will be deleted from SVN again once this job is done.
#     grep '<' en.lang
# will print a TODO list ;-)

test -z "$1" && {
	echo 'Call this script with the $PALANG variable name as parameter!'
	echo 'Example for $PALANG['pAdminEdit_domain_result_error']: '
	echo "    $0 pAdminEdit_domain_result_error"
	exit 1
}

echo before:
grep "'$1'" en.lang

for file in *.lang ; do sed -i "/'$1'/"' s,<span class="error_msg">,,' $file; done
for file in *.lang ; do sed -i "/'$1'/"' s,</span>,,' $file; done

echo after:
grep "'$1'" en.lang

