#!/bin/sh
set -e

. /usr/share/debconf/confmodule

if [ -f /usr/share/dbconfig-common/dpkg/prerm ]; then
        . /usr/share/dbconfig-common/dpkg/prerm
        dbc_go postfixadmin $@
fi

if [ -f /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_version 2.0
	db_get postfixadmin/reconfigure-webserver
	servers="$RET"
	linkname="postfixadmin"
	. /usr/share/wwwconfig-common/confd-link.sh
fi

#DEBHELPER#
