#!/usr/bin/env bash
################################################################################
#
# Bake is a shell script for running CakePHP bake script
# PHP versions 4 and 5
#
# CakePHP(tm) :  Rapid Development Framework (http://www.cakephp.org)
# Copyright 2005-2007, Cake Software Foundation, Inc.
#
# Licensed under The MIT License
# Redistributions of files must retain the above copyright notice.
#
# @filesource
# @copyright		Copyright 2005-2007, Cake Software Foundation, Inc.
# @link				http://www.cakefoundation.org/projects/info/cakephp CakePHP(tm) Project
# @package			cake
# @subpackage		cake.cake.console
# @since				CakePHP(tm) v 1.2.0.5012
# @version			$Revision$
# @modifiedby		$LastChangedBy$
# @lastmodified	$Date$
# @license			http://www.opensource.org/licenses/mit-license.php The MIT License
#
################################################################################

# LIB is expected to be relative to this script (inside the PostfixAdmin sources)
# This breaks if you symlink postfixadmin-cli to /usr/bin or alike. Therefore we
# have to follow the symlink to get the correct path.
self="$0"
test -L "$self" && self="`readlink -f \"$self\"`"

LIB="${self/%postfixadmin-cli/}"

exec php -q "${LIB}postfixadmin-cli.php" "$@"

exit $?
